name: CMake Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive
          fetch-depth: 0
    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
    - name: Configure
      run: cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install -DBUILD_TESTS=ON
    - name: Build
      run: cmake --build _build
    - name: Install
      run: cmake --build _build --target install
    - name: Test
      run: cmake --build _build --target test -- ARGS=--verbose

name: Docker Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t logger .
